name: run crux test suite
on:
  workflow_dispatch:
    inputs:
      branch:
        description: which branch should this workflow be run against. (Default 'main')
        required: false
        default: main
        type: string

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: set up cmake
        uses: lukka/get-cmake@latest

      - name: build executable
        run: |
          mkdir build
          cd build
          sudo apt-get update
          sudo apt-get install -y gcc
          cmake -DCMAKE_BUILD_TYPE=Release ../src
          make
          cd ..

      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crux-executable
          path: build/crux
          retention-days: 1

  run-tests:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: crux-executable
          path: build/

      - name: make crux executable
        run: chmod +x build/crux

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: run tests
        run: |
          cd tests
          python test_runner.py
